name: GothicHousing
main: com.loncha.gothichousing.Main
version: 0.1
load: POSTWORLD
commands:
   miscasas:
      description: Muestra las casas que tienes en propiedad.
      usage: /miscasas
   setcampamento:
      description: Crea un nuevo campamento.
      usage: /setcampamento <nombre>
   cargarbloques:
      description: Carga los bloques del campamento
      usage: /cargarbloques
permissions:
   ghousing.admin:
      description: Permisos de admin para Gothic Housing
      default: op
      